In [204]:
import pandas as pd
from IPython.display import display

pd.options.display.max_rows = 100
pd.options.display.max_columns = 100

In [205]:
# Load the three raw CSV files
print("\n--- Loading datasets ---\n")

volume = pd.read_csv("../data/raw/uk_retail_volume_monthly.csv")
value = pd.read_csv("../data/raw/uk_retail_value_monthly.csv")
commodity = pd.read_csv("../data/raw/uk_retail_commodity.csv")

--- Loading datasets ---

In [206]:
# Inspecting Raw Datasets
print("\n--- Dataset Overview ---\n")

for name, df in [
    ("volume", volume),
    ("value", value),
    ("commodity", commodity),
]:
    print(f"\n--- {name} ---")
    print(f"Shape: {df.shape}")
    print(f"Columns: {df.columns.tolist()}")
    df.info()


display(volume.iloc[:20])
display(value.iloc[:20])
display(commodity.iloc[:20])

--- Dataset Overview ---


--- volume ---
Shape: (940, 34)
Columns: ['1M - CHAINED VOLUME OF RETAIL SALES SEASONALLY ADJUSTED, Index numbers of sales per week and percentage increase on a year earlier, SIC 2007', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33']
<class 'pandas.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 34 columns):
 #   Column                                                                                                                                        Non-Null Count  Dtype
---  ------                                                                                                                                        --------------  -----
 0   1M - CHAINED VOLUME OF RETAIL SALES SEASONALLY ADJUSTED, Index numbers of sales per week and percentage increase on a year earlier, SIC 2007  939 non-null    str
 1   Unnamed: 1                                                                                                                                    728 non-null    str
 2   Unnamed: 2                                                                                                                                    920 non-null    str
 3   Unnamed: 3                                                                                                                                    920 non-null    str
 4   Unnamed: 4                                                                                                                                    920 non-null    str
 5   Unnamed: 5                                                                                                                                    920 non-null    str
 6   Unnamed: 6                                                                                                                                    920 non-null    str
 7   Unnamed: 7                                                                                                                                    920 non-null    str
 8   Unnamed: 8                                                                                                                                    920 non-null    str
 9   Unnamed: 9                                                                                                                                    920 non-null    str
 10  Unnamed: 10                                                                                                                                   920 non-null    str
 11  Unnamed: 11                                                                                                                                   920 non-null    str
 12  Unnamed: 12                                                                                                                                   920 non-null    str
 13  Unnamed: 13                                                                                                                                   920 non-null    str
 14  Unnamed: 14                                                                                                                                   920 non-null    str
 15  Unnamed: 15                                                                                                                                   920 non-null    str
 16  Unnamed: 16                                                                                                                                   920 non-null    str
 17  Unnamed: 17                                                                                                                                   920 non-null    str
 18  Unnamed: 18                                                                                                                                   920 non-null    str
 19  Unnamed: 19                                                                                                                                   920 non-null    str
 20  Unnamed: 20                                                                                                                                   920 non-null    str
 21  Unnamed: 21                                                                                                                                   920 non-null    str
 22  Unnamed: 22                                                                                                                                   920 non-null    str
 23  Unnamed: 23                                                                                                                                   920 non-null    str
 24  Unnamed: 24                                                                                                                                   920 non-null    str
 25  Unnamed: 25                                                                                                                                   920 non-null    str
 26  Unnamed: 26                                                                                                                                   920 non-null    str
 27  Unnamed: 27                                                                                                                                   920 non-null    str
 28  Unnamed: 28                                                                                                                                   920 non-null    str
 29  Unnamed: 29                                                                                                                                   920 non-null    str
 30  Unnamed: 30                                                                                                                                   920 non-null    str
 31  Unnamed: 31                                                                                                                                   920 non-null    str
 32  Unnamed: 32                                                                                                                                   920 non-null    str
 33  Unnamed: 33                                                                                                                                   728 non-null    str
dtypes: str(34)
memory usage: 249.8 KB

--- value ---
Shape: (940, 34)
Columns: ['2M - VALUE OF RETAIL SALES AT CURRENT PRICES SEASONALLY ADJUSTED, Index numbers of sales per week and percentage increase on a year earlier, SIC 2007', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33']
<class 'pandas.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 34 columns):
 #   Column                                                                                                                                                 Non-Null Count  Dtype
---  ------                                                                                                                                                 --------------  -----
 0   2M - VALUE OF RETAIL SALES AT CURRENT PRICES SEASONALLY ADJUSTED, Index numbers of sales per week and percentage increase on a year earlier, SIC 2007  939 non-null    str
 1   Unnamed: 1                                                                                                                                             728 non-null    str
 2   Unnamed: 2                                                                                                                                             920 non-null    str
 3   Unnamed: 3                                                                                                                                             920 non-null    str
 4   Unnamed: 4                                                                                                                                             920 non-null    str
 5   Unnamed: 5                                                                                                                                             920 non-null    str
 6   Unnamed: 6                                                                                                                                             920 non-null    str
 7   Unnamed: 7                                                                                                                                             920 non-null    str
 8   Unnamed: 8                                                                                                                                             920 non-null    str
 9   Unnamed: 9                                                                                                                                             920 non-null    str
 10  Unnamed: 10                                                                                                                                            920 non-null    str
 11  Unnamed: 11                                                                                                                                            920 non-null    str
 12  Unnamed: 12                                                                                                                                            920 non-null    str
 13  Unnamed: 13                                                                                                                                            920 non-null    str
 14  Unnamed: 14                                                                                                                                            920 non-null    str
 15  Unnamed: 15                                                                                                                                            920 non-null    str
 16  Unnamed: 16                                                                                                                                            920 non-null    str
 17  Unnamed: 17                                                                                                                                            920 non-null    str
 18  Unnamed: 18                                                                                                                                            920 non-null    str
 19  Unnamed: 19                                                                                                                                            920 non-null    str
 20  Unnamed: 20                                                                                                                                            920 non-null    str
 21  Unnamed: 21                                                                                                                                            920 non-null    str
 22  Unnamed: 22                                                                                                                                            920 non-null    str
 23  Unnamed: 23                                                                                                                                            920 non-null    str
 24  Unnamed: 24                                                                                                                                            920 non-null    str
 25  Unnamed: 25                                                                                                                                            920 non-null    str
 26  Unnamed: 26                                                                                                                                            920 non-null    str
 27  Unnamed: 27                                                                                                                                            920 non-null    str
 28  Unnamed: 28                                                                                                                                            920 non-null    str
 29  Unnamed: 29                                                                                                                                            920 non-null    str
 30  Unnamed: 30                                                                                                                                            920 non-null    str
 31  Unnamed: 31                                                                                                                                            920 non-null    str
 32  Unnamed: 32                                                                                                                                            920 non-null    str
 33  Unnamed: 33                                                                                                                                            728 non-null    str
dtypes: str(34)
memory usage: 249.8 KB

--- commodity ---
Shape: (1606, 6)
Columns: ['5 - VALUE OF RETAIL SALES BY COMMODITY AT CURRENT PRICES NON-SEASONALLY ADJUSTED', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5']
<class 'pandas.DataFrame'>
RangeIndex: 1606 entries, 0 to 1605
Data columns (total 6 columns):
 #   Column                                                                            Non-Null Count  Dtype
---  ------                                                                            --------------  -----
 0   5 - VALUE OF RETAIL SALES BY COMMODITY AT CURRENT PRICES NON-SEASONALLY ADJUSTED  1602 non-null   str
 1   Unnamed: 1                                                                        1563 non-null   str
 2   Unnamed: 2                                                                        1440 non-null   str
 3   Unnamed: 3                                                                        1440 non-null   str
 4   Unnamed: 4                                                                        1440 non-null   str
 5   Unnamed: 5                                                                        1440 non-null   str
dtypes: str(6)
memory usage: 75.4 KB

,"1M - CHAINED VOLUME OF RETAIL SALES SEASONALLY ADJUSTED, Index numbers of sales per week and percentage increase on a year earlier, SIC 2007",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,This worksheet contains two tables presented v...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Source: Retail Sales Index,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Index 2023=100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,The monthly period consists of 4 weeks except ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Some cells in this table are empty because dat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Index number of sales per week,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Time Period,"All Retailing, Including Automotive Fuel","All Retailing, Excluding Automotive Fuel",Predominantly Food Stores,Non-specialised Food Stores,Specialist Food Stores,"Alcoholic Drinks, Other Beverages and Tobacco",Predominantly Non-food Stores,Non-Specialised Predominantly Non-Food Stores,"Textile, Clothing, Footwear and Leather",Textiles,Clothing,Footwear and Leather Goods,Household Goods Stores,"Furniture, Lighting etc",Electrical Household Appliances,"Hardware, Paints and Glass",Music and video recordings and equipment,Other Specialised Non-food Stores,Dispensing Chemists,Medical Goods,Cosmetic & Toilet Articles,Computers & Telecomms Equipment,Floor Coverings,"Books, Newspapers & Periodicals","Sports Equipment, Games & Toys","Flowers, plants, seeds, fertilisers and pet foods",Watches & Jewellery,Other Retail Sale of New Goods in Specialised ...,Second-hand Goods,Non-store Retail,Mail Order,Other Non-store Retail,Automotive Fuel
7,Sales in 2023,"(£509,445m)","(£461,489m)","(£201,285m)","(£184,104m)","(£13,803m)","(£3,378m)","(£194,112m)","(£37,105m)","(£56,341m)",(£802m),"(£48,911m)","(£6,628m)","(£37,261m)","(£16,712m)","(£6,444m)","(£13,223m)",(£881m),"(£63,405m)","(£1,515m)","(£1,196m)","(£6,729m)","(£4,031m)","(£2,766m)","(£3,456m)","(£13,490m)","(£6,563m)","(£8,299m)","(£11,761m)","(£3,600m)","(£66,092m)","(£63,064m)","(£3,028m)","(£47,956m)"
8,AGG/SIC,AGG21,AGG21X,AGG1,47.11,AGG26,AGG27,AGG12,47.19,AGG5,47.51,47.71,47.72,AGG7,47.59,47.54,47.52,AGG31,AGG13,47.73,47.74,47.75,AGG32,47.53,AGG35,AGG33,47.76,47.77,47.78,47.79,AGG14,47.91,Agg 11,47.3
9,Percentage Weight,100,88.93,37.57,34.57,2.26,0.74,38.33,7.11,10.61,0.21,9.28,1.12,7.62,3.34,1.41,2.71,0.16,12.99,0.33,0.26,1.15,0.82,0.56,0.68,2.87,1.39,1.72,2.43,0.78,13.03,12.39,0.64,11.07
10,Dataset identifier code,J5EK,J467,EAPT,JO59,JO5U,JO5V,EAPV,EAPU,EAPX,JO5C,JO5I,JO5J,EAPY,JO5G,JO5F,JO5D,JO5Y,EAPW,JO5K,JO5L,JO5M,JO5Z,JO5E,JO64,JO62,JO5N,JO5O,JO5P,JO5Q,J5DZ,JO5R,JO5S,JO5A
11,1988 Jan,NaN,51.4,63.8,50.0,156.0,454.3,48.8,50.9,36.9,109.3,34.4,44.2,66.9,81.6,42.1,72.6,199.1,49.5,154.1,57.3,24.2,28.1,199.4,284.5,14.3,37.2,41.9,55.2,56.5,28.1,16.2,412.9,NaN
12,1988 Feb,NaN,50.3,63.5,50.0,152.4,446.3,47.5,50.3,36.1,108.2,33.5,44.6,65.1,81.5,39.8,70.7,189.5,47.4,143.9,52.5,23.6,25.2,196.9,280.9,13.8,35.9,40.4,53.2,55.7,26.8,15.2,402.9,NaN
13,1988 Mar,NaN,50.3,63.1,49.6,149.9,455.4,47.6,50.4,35.7,106.3,33.3,43.0,65.6,81.6,40.7,70.2,194.8,47.8,155.1,54.9,23.9,25.1,194.8,286.0,13.8,35.9,40.7,54.3,54.2,26.9,15.4,400.4,NaN
14,1988 Apr,NaN,51.6,64.3,50.8,152.9,452.6,48.9,51.0,36.5,106.6,34.0,44.1,67.2,85.1,41.0,71.3,197.0,49.9,154.4,55.5,24.3,28.9,205.2,288.8,14.4,37.1,41.4,54.4,57.1,28.5,16.5,416.4,NaN
15,1988 May,NaN,51.3,63.7,50.3,151.5,450.7,48.6,50.8,36.1,108.3,33.5,44.5,67.6,85.5,41.5,71.6,198.0,49.4,158.6,56.8,24.7,27.5,207.2,286.4,14.2,37.2,41.1,54.0,57.8,28.2,15.9,432.8,NaN
16,1988 Jun,NaN,51.7,63.7,50.3,149.4,455.4,49.5,51.6,37.2,115.6,34.6,44.3,67.8,86.3,40.4,74.8,192.0,50.3,161.2,57.1,24.3,27.7,210.5,296.0,14.6,37.9,42.1,55.4,57.8,28.4,16.4,418.1,NaN
17,1988 Jul,NaN,52.5,63.4,50.1,149.8,447.5,50.8,51.7,37.2,122.0,34.5,44.2,72.9,91.4,45.5,76.4,218.3,51.5,157.9,57.1,24.6,30.1,220.5,291.0,14.9,38.2,42.4,55.7,62.6,28.8,16.6,421.7,NaN
18,1988 Aug,NaN,52.5,64.0,50.6,150.8,456.1,50.5,51.8,37.4,119.6,34.8,44.6,70.7,87.4,43.4,77.6,208.4,51.6,163.4,56.1,25.6,29.6,210.2,293.7,15.1,38.8,42.9,56.4,61.7,28.6,16.5,416.9,NaN
19,1988 Sep,NaN,52.1,63.7,50.4,149.6,453.0,50.3,52.0,37.5,119.0,34.9,44.6,70.1,86.5,43.1,77.2,206.9,50.9,161.4,55.2,25.3,28.9,208.1,292.9,14.9,38.0,42.3,55.6,60.7,27.9,16.0,409.7,NaN

,"2M - VALUE OF RETAIL SALES AT CURRENT PRICES SEASONALLY ADJUSTED, Index numbers of sales per week and percentage increase on a year earlier, SIC 2007",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,This worksheet contains two tables presented v...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Source: Retail Sales Index,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Index 2023=100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,The monthly period consists of 4 weeks except ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Some cells in this table are empty because dat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Index number of sales per week,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Time Period,"All Retailing, Including Automotive Fuel","All Retailing, Excluding Automotive Fuel",Predominantly Food Stores,Non-specialised Food Stores,Specialist Food Stores,"Alcoholic Drinks, Other Beverages and Tobacco",Predominantly Non-food Stores,Non-Specialised Predominantly Non-Food Stores,"Textile, Clothing, Footwear and Leather",Textiles,Clothing,Footwear and Leather Goods,Household Goods Stores,"Furniture, Lighting etc",Electrical Household Appliances,"Hardware, Paints and Glass",Music and video recordings and equipment,Other Specialised Non-food Stores,Dispensing Chemists,Medical Goods,Cosmetic & Toilet Articles,Computers & Telecomms Equipment,Floor Coverings,"Books, Newspapers & Periodicals","Sports Equipment, Games & Toys","Flowers, plants, seeds, fertilisers and pet foods",Watches & Jewellery,Other Retail Sale of New Goods in Specialised ...,Second-hand Goods,Non-store Retail,Mail Order,Other Non-store Retail,Automotive Fuel
7,Sales in 2023,"(£509,445m)","(£461,489m)","(£201,285m)","(£184,104m)","(£13,803m)","(£3,378m)","(£194,112m)","(£37,105m)","(£56,341m)",(£802m),"(£48,911m)","(£6,628m)","(£37,261m)","(£16,712m)","(£6,444m)","(£13,223m)",(£881m),"(£63,405m)","(£1,515m)","(£1,196m)","(£6,729m)","(£4,031m)","(£2,766m)","(£3,456m)","(£13,490m)","(£6,563m)","(£8,299m)","(£11,761m)","(£3,600m)","(£66,092m)","(£63,064m)","(£3,028m)","(£47,956m)"
8,AGG/SIC,AGG21,AGG21X,AGG1,47.11,AGG26,AGG27,AGG12,47.19,AGG5,47.51,47.71,47.72,AGG7,47.59,47.54,47.52,AGG31,AGG13,47.73,47.74,47.75,AGG32,47.53,AGG35,AGG33,47.76,47.77,47.78,47.79,AGG14,47.91,Agg 11,47.3
9,Percentage Weight,100,88.93,37.57,34.57,2.26,0.74,38.33,7.11,10.61,0.21,9.28,1.12,7.62,3.34,1.41,2.71,0.16,12.99,0.33,0.26,1.15,0.82,0.56,0.68,2.87,1.39,1.72,2.43,0.78,13.03,12.39,0.64,11.07
10,Dataset identifier code,J5C4,J468,EAQW,JO2F,JO32,JO33,EAQY,EAQX,EARA,JO2I,JO2O,JO2P,EARB,JO2M,JO2L,JO2J,JO36,EAQZ,JO2Q,JO2R,JO2S,JO37,JO2K,JO3A,JO38,JO2T,JO2U,JO2V,JO2W,J5BI,JO2X,JO2Y,JO2G
11,1988 Jan,NaN,27.0,23.3,18.3,61.2,136.5,34.9,30.2,31.9,88.5,29.3,44.3,48.6,41.4,85.1,32.6,159.6,32.3,64.9,23.9,11.8,87.8,72.9,87.5,18.4,18.4,15.6,33.6,26.0,15.3,10.8,110.5,NaN
12,1988 Feb,NaN,26.6,23.2,18.4,59.8,133.7,34.2,30.0,31.5,86.1,28.8,44.8,47.5,41.9,80.4,31.7,151.4,31.1,60.6,18.7,11.3,78.0,72.5,88.5,17.8,17.9,15.2,32.6,25.8,14.8,10.3,107.9,NaN
13,1988 Mar,NaN,26.6,23.2,18.4,59.4,136.8,34.2,30.1,31.2,85.4,28.7,43.3,47.9,41.8,82.3,31.6,154.6,31.1,65.5,21.0,11.5,73.9,71.4,89.7,17.7,18.0,15.2,33.2,25.1,14.8,10.4,108.1,NaN
14,1988 Apr,NaN,27.4,23.7,18.9,60.2,136.1,35.1,30.4,31.5,83.3,28.9,44.3,48.7,43.3,82.6,31.9,156.4,33.1,65.8,22.2,11.8,96.3,75.2,90.7,18.4,18.5,15.6,33.2,26.3,15.9,11.2,112.2,NaN
15,1988 May,NaN,27.3,23.5,18.7,59.9,136.2,35.3,30.5,32.1,85.2,29.4,45.6,49.4,43.8,84.2,32.5,157.2,32.7,67.8,22.1,12.2,87.1,75.9,90.5,18.4,18.6,15.5,33.3,26.7,15.6,10.7,116.6,NaN
16,1988 Jun,NaN,27.5,23.5,18.7,59.4,137.0,35.7,31.0,32.6,89.4,30.1,44.4,49.5,44.0,82.2,33.5,153.8,33.0,68.4,21.8,11.9,87.2,76.3,93.3,18.6,18.7,15.8,34.0,26.7,15.8,11.1,113.3,NaN
17,1988 Jul,NaN,28.1,23.5,18.7,60.1,135.0,37.0,31.6,32.9,95.9,30.2,45.2,53.3,47.1,91.4,34.4,173.1,34.3,67.8,23.4,12.0,98.2,82.5,92.5,18.8,19.0,16.0,34.4,29.0,16.1,11.3,115.3,NaN
18,1988 Aug,NaN,28.2,23.8,19.0,60.6,138.6,36.8,31.4,33.1,93.2,30.4,45.5,52.2,45.5,88.6,35.2,165.8,34.3,71.1,20.5,12.7,94.3,78.1,94.3,19.2,19.3,16.4,35.0,28.7,16.1,11.3,116.1,NaN
19,1988 Sep,NaN,28.0,23.8,19.0,60.5,137.9,36.5,31.5,33.1,92.1,30.4,45.5,51.2,44.6,86.3,35.1,163.6,33.9,70.3,21.4,12.5,91.9,78.0,93.8,18.9,19.0,16.1,34.5,28.1,15.5,10.7,114.3,NaN

,5 - VALUE OF RETAIL SALES BY COMMODITY AT CURRENT PRICES NON-SEASONALLY ADJUSTED,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,This worksheet contains five tables presented ...,NaN,NaN,NaN,NaN,NaN
1,Source: Retail Sales Index,NaN,NaN,NaN,NaN,NaN
2,Index 2023=100,NaN,NaN,NaN,NaN,NaN
3,The monthly period consists of 4 weeks except ...,NaN,NaN,NaN,NaN,NaN
4,Some cells in this table are empty because dat...,NaN,NaN,NaN,NaN,NaN
5,Estimates in this table have been produced by ...,NaN,NaN,NaN,NaN,NaN
6,The quarterly indices are the weighted average...,NaN,NaN,NaN,NaN,NaN
7,"In July 2018, we increased our sample for the ...",NaN,NaN,NaN,NaN,NaN
8,Index numbers of sales per week - Annually,NaN,NaN,NaN,NaN,NaN
9,Time Period,Total excluding fuel,"Food, drink and tobacco [Note 3]",Clothing and footwear,Household goods [Note 3],Other non-food [Note 3]
10,Average weekly sales in 2023 (£ millions),"8,875","3,741","1,520","1,485","2,129"
11,AGG/SIC,J43S,EAWN,EAWO,EAWP,EAWQ
12,1988,27.8,NaN,NaN,NaN,NaN
13,1989,29.9,NaN,NaN,NaN,NaN
14,1990,32.0,NaN,NaN,NaN,NaN
15,1991,33.1,32.8,30.3,39.1,31.3
16,1992,34.1,34.3,30.8,39.3,32.5
17,1993,35.7,35.7,32.3,41.8,33.8
18,1994,37.2,37.0,34.2,43.4,35.3
19,1995,38.3,38.6,34.8,44.4,36.2

In [207]:
# Extract Metadata
def extract_metadata(df, start_row, end_row):
    return df.iloc[start_row:end_row].copy()


volume_metadata = extract_metadata(volume, 0, 11)
value_metadata = extract_metadata(value, 0, 11)
commodity_metadata = extract_metadata(commodity, 0, 12)

display(volume_metadata)
display(value_metadata)
display(commodity_metadata)

,"1M - CHAINED VOLUME OF RETAIL SALES SEASONALLY ADJUSTED, Index numbers of sales per week and percentage increase on a year earlier, SIC 2007",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,This worksheet contains two tables presented v...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Source: Retail Sales Index,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Index 2023=100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,The monthly period consists of 4 weeks except ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Some cells in this table are empty because dat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Index number of sales per week,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Time Period,"All Retailing, Including Automotive Fuel","All Retailing, Excluding Automotive Fuel",Predominantly Food Stores,Non-specialised Food Stores,Specialist Food Stores,"Alcoholic Drinks, Other Beverages and Tobacco",Predominantly Non-food Stores,Non-Specialised Predominantly Non-Food Stores,"Textile, Clothing, Footwear and Leather",Textiles,Clothing,Footwear and Leather Goods,Household Goods Stores,"Furniture, Lighting etc",Electrical Household Appliances,"Hardware, Paints and Glass",Music and video recordings and equipment,Other Specialised Non-food Stores,Dispensing Chemists,Medical Goods,Cosmetic & Toilet Articles,Computers & Telecomms Equipment,Floor Coverings,"Books, Newspapers & Periodicals","Sports Equipment, Games & Toys","Flowers, plants, seeds, fertilisers and pet foods",Watches & Jewellery,Other Retail Sale of New Goods in Specialised ...,Second-hand Goods,Non-store Retail,Mail Order,Other Non-store Retail,Automotive Fuel
7,Sales in 2023,"(£509,445m)","(£461,489m)","(£201,285m)","(£184,104m)","(£13,803m)","(£3,378m)","(£194,112m)","(£37,105m)","(£56,341m)",(£802m),"(£48,911m)","(£6,628m)","(£37,261m)","(£16,712m)","(£6,444m)","(£13,223m)",(£881m),"(£63,405m)","(£1,515m)","(£1,196m)","(£6,729m)","(£4,031m)","(£2,766m)","(£3,456m)","(£13,490m)","(£6,563m)","(£8,299m)","(£11,761m)","(£3,600m)","(£66,092m)","(£63,064m)","(£3,028m)","(£47,956m)"
8,AGG/SIC,AGG21,AGG21X,AGG1,47.11,AGG26,AGG27,AGG12,47.19,AGG5,47.51,47.71,47.72,AGG7,47.59,47.54,47.52,AGG31,AGG13,47.73,47.74,47.75,AGG32,47.53,AGG35,AGG33,47.76,47.77,47.78,47.79,AGG14,47.91,Agg 11,47.3
9,Percentage Weight,100,88.93,37.57,34.57,2.26,0.74,38.33,7.11,10.61,0.21,9.28,1.12,7.62,3.34,1.41,2.71,0.16,12.99,0.33,0.26,1.15,0.82,0.56,0.68,2.87,1.39,1.72,2.43,0.78,13.03,12.39,0.64,11.07
10,Dataset identifier code,J5EK,J467,EAPT,JO59,JO5U,JO5V,EAPV,EAPU,EAPX,JO5C,JO5I,JO5J,EAPY,JO5G,JO5F,JO5D,JO5Y,EAPW,JO5K,JO5L,JO5M,JO5Z,JO5E,JO64,JO62,JO5N,JO5O,JO5P,JO5Q,J5DZ,JO5R,JO5S,JO5A

,"2M - VALUE OF RETAIL SALES AT CURRENT PRICES SEASONALLY ADJUSTED, Index numbers of sales per week and percentage increase on a year earlier, SIC 2007",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,This worksheet contains two tables presented v...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Source: Retail Sales Index,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Index 2023=100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,The monthly period consists of 4 weeks except ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Some cells in this table are empty because dat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Index number of sales per week,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Time Period,"All Retailing, Including Automotive Fuel","All Retailing, Excluding Automotive Fuel",Predominantly Food Stores,Non-specialised Food Stores,Specialist Food Stores,"Alcoholic Drinks, Other Beverages and Tobacco",Predominantly Non-food Stores,Non-Specialised Predominantly Non-Food Stores,"Textile, Clothing, Footwear and Leather",Textiles,Clothing,Footwear and Leather Goods,Household Goods Stores,"Furniture, Lighting etc",Electrical Household Appliances,"Hardware, Paints and Glass",Music and video recordings and equipment,Other Specialised Non-food Stores,Dispensing Chemists,Medical Goods,Cosmetic & Toilet Articles,Computers & Telecomms Equipment,Floor Coverings,"Books, Newspapers & Periodicals","Sports Equipment, Games & Toys","Flowers, plants, seeds, fertilisers and pet foods",Watches & Jewellery,Other Retail Sale of New Goods in Specialised ...,Second-hand Goods,Non-store Retail,Mail Order,Other Non-store Retail,Automotive Fuel
7,Sales in 2023,"(£509,445m)","(£461,489m)","(£201,285m)","(£184,104m)","(£13,803m)","(£3,378m)","(£194,112m)","(£37,105m)","(£56,341m)",(£802m),"(£48,911m)","(£6,628m)","(£37,261m)","(£16,712m)","(£6,444m)","(£13,223m)",(£881m),"(£63,405m)","(£1,515m)","(£1,196m)","(£6,729m)","(£4,031m)","(£2,766m)","(£3,456m)","(£13,490m)","(£6,563m)","(£8,299m)","(£11,761m)","(£3,600m)","(£66,092m)","(£63,064m)","(£3,028m)","(£47,956m)"
8,AGG/SIC,AGG21,AGG21X,AGG1,47.11,AGG26,AGG27,AGG12,47.19,AGG5,47.51,47.71,47.72,AGG7,47.59,47.54,47.52,AGG31,AGG13,47.73,47.74,47.75,AGG32,47.53,AGG35,AGG33,47.76,47.77,47.78,47.79,AGG14,47.91,Agg 11,47.3
9,Percentage Weight,100,88.93,37.57,34.57,2.26,0.74,38.33,7.11,10.61,0.21,9.28,1.12,7.62,3.34,1.41,2.71,0.16,12.99,0.33,0.26,1.15,0.82,0.56,0.68,2.87,1.39,1.72,2.43,0.78,13.03,12.39,0.64,11.07
10,Dataset identifier code,J5C4,J468,EAQW,JO2F,JO32,JO33,EAQY,EAQX,EARA,JO2I,JO2O,JO2P,EARB,JO2M,JO2L,JO2J,JO36,EAQZ,JO2Q,JO2R,JO2S,JO37,JO2K,JO3A,JO38,JO2T,JO2U,JO2V,JO2W,J5BI,JO2X,JO2Y,JO2G

,5 - VALUE OF RETAIL SALES BY COMMODITY AT CURRENT PRICES NON-SEASONALLY ADJUSTED,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,This worksheet contains five tables presented ...,NaN,NaN,NaN,NaN,NaN
1,Source: Retail Sales Index,NaN,NaN,NaN,NaN,NaN
2,Index 2023=100,NaN,NaN,NaN,NaN,NaN
3,The monthly period consists of 4 weeks except ...,NaN,NaN,NaN,NaN,NaN
4,Some cells in this table are empty because dat...,NaN,NaN,NaN,NaN,NaN
5,Estimates in this table have been produced by ...,NaN,NaN,NaN,NaN,NaN
6,The quarterly indices are the weighted average...,NaN,NaN,NaN,NaN,NaN
7,"In July 2018, we increased our sample for the ...",NaN,NaN,NaN,NaN,NaN
8,Index numbers of sales per week - Annually,NaN,NaN,NaN,NaN,NaN
9,Time Period,Total excluding fuel,"Food, drink and tobacco [Note 3]",Clothing and footwear,Household goods [Note 3],Other non-food [Note 3]
10,Average weekly sales in 2023 (£ millions),"8,875","3,741","1,520","1,485","2,129"
11,AGG/SIC,J43S,EAWN,EAWO,EAWP,EAWQ

In [208]:
# Inspecting Metadata
def inspect_metadata(metadata):
    for i in range(len(metadata)):
        print(i, metadata.iloc[i].tolist())


print("\n--- Inspect Volume Metadata ---")
inspect_metadata(volume_metadata)

print("\n--- Inspect Value Metadata ---")
inspect_metadata(value_metadata)

print("\n--- Inspect Commodity Metadata ---")
inspect_metadata(commodity_metadata)

--- Inspect Volume Metadata ---
0 ['This worksheet contains two tables presented vertically with one above the other and a blank row between the two tables', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
1 ['Source: Retail Sales Index', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
2 ['Index 2023=100', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
3 ['The monthly period consists of 4 weeks except for March, June, September and December which are 5 weeks. January 2025 is also a 5 week period.', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
4 ['Some cells in this table are empty because data was not collected for these variables at these time points.', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
5 ['Index number of sales per week', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
6 ['Time Period', 'All Retailing, Including Automotive Fuel', 'All Retailing, Excluding Automotive Fuel', 'Predominantly Food Stores', 'Non-specialised Food Stores', 'Specialist Food Stores', 'Alcoholic Drinks, Other Beverages and Tobacco', 'Predominantly Non-food Stores', 'Non-Specialised Predominantly Non-Food Stores', 'Textile, Clothing, Footwear and Leather', 'Textiles', 'Clothing', 'Footwear and Leather Goods', 'Household Goods Stores', 'Furniture, Lighting etc', 'Electrical Household Appliances', 'Hardware, Paints and Glass', 'Music and video recordings and equipment', 'Other Specialised Non-food Stores', 'Dispensing Chemists', 'Medical Goods', 'Cosmetic & Toilet Articles', 'Computers & Telecomms Equipment', 'Floor Coverings', 'Books, Newspapers & Periodicals', 'Sports Equipment, Games & Toys', 'Flowers, plants, seeds, fertilisers and pet foods', 'Watches & Jewellery', 'Other Retail Sale of New Goods in Specialised Stores', 'Second-hand Goods', 'Non-store Retail', 'Mail Order', 'Other Non-store Retail', 'Automotive Fuel']
7 ['Sales in 2023', '(£509,445m)', '(£461,489m)', '(£201,285m)', '(£184,104m)', '(£13,803m)', '(£3,378m)', '(£194,112m)', '(£37,105m)', '(£56,341m)', '(£802m)', '(£48,911m)', '(£6,628m)', '(£37,261m)', '(£16,712m)', '(£6,444m)', '(£13,223m)', '(£881m)', '(£63,405m)', '(£1,515m)', '(£1,196m)', '(£6,729m)', '(£4,031m)', '(£2,766m)', '(£3,456m)', '(£13,490m)', '(£6,563m)', '(£8,299m)', '(£11,761m)', '(£3,600m)', '(£66,092m)', '(£63,064m)', '(£3,028m)', '(£47,956m)']
8 ['AGG/SIC', 'AGG21', 'AGG21X', 'AGG1', '47.11', 'AGG26', 'AGG27', 'AGG12', '47.19', 'AGG5', '47.51', '47.71', '47.72', 'AGG7', '47.59', '47.54', '47.52', 'AGG31', 'AGG13', '47.73', '47.74', '47.75', 'AGG32', '47.53', 'AGG35', 'AGG33', '47.76', '47.77', '47.78', '47.79', 'AGG14', '47.91', 'Agg 11', '47.3']
9 ['Percentage Weight', '100', '88.93', '37.57', '34.57', '2.26', '0.74', '38.33', '7.11', '10.61', '0.21', '9.28', '1.12', '7.62', '3.34', '1.41', '2.71', '0.16', '12.99', '0.33', '0.26', '1.15', '0.82', '0.56', '0.68', '2.87', '1.39', '1.72', '2.43', '0.78', '13.03', '12.39', '0.64', '11.07']
10 ['Dataset identifier code', 'J5EK', 'J467', 'EAPT', 'JO59', 'JO5U', 'JO5V', 'EAPV', 'EAPU', 'EAPX', 'JO5C', 'JO5I', 'JO5J', 'EAPY', 'JO5G', 'JO5F', 'JO5D', 'JO5Y', 'EAPW', 'JO5K', 'JO5L', 'JO5M', 'JO5Z', 'JO5E', 'JO64', 'JO62', 'JO5N', 'JO5O', 'JO5P', 'JO5Q', 'J5DZ', 'JO5R', 'JO5S', 'JO5A']

--- Inspect Value Metadata ---
0 ['This worksheet contains two tables presented vertically with one above the other and a blank row between the two tables', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
1 ['Source: Retail Sales Index', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
2 ['Index 2023=100', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
3 ['The monthly period consists of 4 weeks except for March, June, September and December which are 5 weeks. January 2025 is also a 5 week period.', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
4 ['Some cells in this table are empty because data was not collected for these variables at these time points.', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
5 ['Index number of sales per week', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
6 ['Time Period', 'All Retailing, Including Automotive Fuel', 'All Retailing, Excluding Automotive Fuel', 'Predominantly Food Stores', 'Non-specialised Food Stores', 'Specialist Food Stores', 'Alcoholic Drinks, Other Beverages and Tobacco', 'Predominantly Non-food Stores', 'Non-Specialised Predominantly Non-Food Stores', 'Textile, Clothing, Footwear and Leather', 'Textiles', 'Clothing', 'Footwear and Leather Goods', 'Household Goods Stores', 'Furniture, Lighting etc', 'Electrical Household Appliances', 'Hardware, Paints and Glass', 'Music and video recordings and equipment', 'Other Specialised Non-food Stores', 'Dispensing Chemists', 'Medical Goods', 'Cosmetic & Toilet Articles', 'Computers & Telecomms Equipment', 'Floor Coverings', 'Books, Newspapers & Periodicals', 'Sports Equipment, Games & Toys', 'Flowers, plants, seeds, fertilisers and pet foods', 'Watches & Jewellery', 'Other Retail Sale of New Goods in Specialised Stores', 'Second-hand Goods', 'Non-store Retail', 'Mail Order', 'Other Non-store Retail', 'Automotive Fuel']
7 ['Sales in 2023', '(£509,445m)', '(£461,489m)', '(£201,285m)', '(£184,104m)', '(£13,803m)', '(£3,378m)', '(£194,112m)', '(£37,105m)', '(£56,341m)', '(£802m)', '(£48,911m)', '(£6,628m)', '(£37,261m)', '(£16,712m)', '(£6,444m)', '(£13,223m)', '(£881m)', '(£63,405m)', '(£1,515m)', '(£1,196m)', '(£6,729m)', '(£4,031m)', '(£2,766m)', '(£3,456m)', '(£13,490m)', '(£6,563m)', '(£8,299m)', '(£11,761m)', '(£3,600m)', '(£66,092m)', '(£63,064m)', '(£3,028m)', '(£47,956m)']
8 ['AGG/SIC', 'AGG21', 'AGG21X', 'AGG1', '47.11', 'AGG26', 'AGG27', 'AGG12', '47.19', 'AGG5', '47.51', '47.71', '47.72', 'AGG7', '47.59', '47.54', '47.52', 'AGG31', 'AGG13', '47.73', '47.74', '47.75', 'AGG32', '47.53', 'AGG35', 'AGG33', '47.76', '47.77', '47.78', '47.79', 'AGG14', '47.91', 'Agg 11', '47.3']
9 ['Percentage Weight', '100', '88.93', '37.57', '34.57', '2.26', '0.74', '38.33', '7.11', '10.61', '0.21', '9.28', '1.12', '7.62', '3.34', '1.41', '2.71', '0.16', '12.99', '0.33', '0.26', '1.15', '0.82', '0.56', '0.68', '2.87', '1.39', '1.72', '2.43', '0.78', '13.03', '12.39', '0.64', '11.07']
10 ['Dataset identifier code', 'J5C4', 'J468', 'EAQW', 'JO2F', 'JO32', 'JO33', 'EAQY', 'EAQX', 'EARA', 'JO2I', 'JO2O', 'JO2P', 'EARB', 'JO2M', 'JO2L', 'JO2J', 'JO36', 'EAQZ', 'JO2Q', 'JO2R', 'JO2S', 'JO37', 'JO2K', 'JO3A', 'JO38', 'JO2T', 'JO2U', 'JO2V', 'JO2W', 'J5BI', 'JO2X', 'JO2Y', 'JO2G']

--- Inspect Commodity Metadata ---
0 ['This worksheet contains five tables presented vertically with a blank row between each table', nan, nan, nan, nan, nan]
1 ['Source: Retail Sales Index', nan, nan, nan, nan, nan]
2 ['Index 2023=100', nan, nan, nan, nan, nan]
3 ['The monthly period consists of 4 weeks except for March, June, September and December which are 5 weeks. January 2025 is also a 5 week period.', nan, nan, nan, nan, nan]
4 ['Some cells in this table are empty because data was not collected for these variables at these time points.', nan, nan, nan, nan, nan]
5 ['Estimates in this table have been produced by combining a breakdown of commodity sales from 56 large retailers with total sales from other retailers.', nan, nan, nan, nan, nan]
6 ['The quarterly indices are the weighted averages of the monthly indices for the months within the quarter, the weights being the number of weeks in each monthly period.', nan, nan, nan, nan, nan]
7 ['In July 2018, we increased our sample for the commodity breakdown from 31 to 54 retailers to improve coverage and better represent the commodities sold. Growth rates may not be comparable as a result. This does not impact the main retail sales data.', nan, nan, nan, nan, nan]
8 ['Index numbers of sales per week - Annually', nan, nan, nan, nan, nan]
9 ['Time Period', 'Total excluding fuel', 'Food, drink and tobacco [Note 3]', 'Clothing and footwear', 'Household goods [Note 3]', 'Other non-food [Note 3]']
10 ['Average weekly sales in 2023 (£ millions)', '8,875', '3,741', '1,520', '1,485', '2,129']
11 ['AGG/SIC', 'J43S', 'EAWN', 'EAWO', 'EAWP', 'EAWQ']

In [209]:
# Transform Retail Metadate
def transform_retail_metadata(metadata):
    categories = pd.DataFrame({
        "category_name": metadata.iloc[6, 1:].values,
        "sales_2023": metadata.iloc[7, 1:].values,
        "agg_sic": metadata.iloc[8, 1:].values,
        "percentage_weight": metadata.iloc[9, 1:].values,
        "dataset_code": metadata.iloc[10, 1:].values,
    })

    return categories


volume_categories = transform_retail_metadata(volume_metadata)
value_categories = transform_retail_metadata(value_metadata)

display(volume_categories)
display(value_categories)

,category_name,sales_2023,agg_sic,percentage_weight,dataset_code
0,"All Retailing, Including Automotive Fuel","(£509,445m)",AGG21,100,J5EK
1,"All Retailing, Excluding Automotive Fuel","(£461,489m)",AGG21X,88.93,J467
2,Predominantly Food Stores,"(£201,285m)",AGG1,37.57,EAPT
3,Non-specialised Food Stores,"(£184,104m)",47.11,34.57,JO59
4,Specialist Food Stores,"(£13,803m)",AGG26,2.26,JO5U
5,"Alcoholic Drinks, Other Beverages and Tobacco","(£3,378m)",AGG27,0.74,JO5V
6,Predominantly Non-food Stores,"(£194,112m)",AGG12,38.33,EAPV
7,Non-Specialised Predominantly Non-Food Stores,"(£37,105m)",47.19,7.11,EAPU
8,"Textile, Clothing, Footwear and Leather","(£56,341m)",AGG5,10.61,EAPX
9,Textiles,(£802m),47.51,0.21,JO5C
10,Clothing,"(£48,911m)",47.71,9.28,JO5I
11,Footwear and Leather Goods,"(£6,628m)",47.72,1.12,JO5J
12,Household Goods Stores,"(£37,261m)",AGG7,7.62,EAPY
13,"Furniture, Lighting etc","(£16,712m)",47.59,3.34,JO5G
14,Electrical Household Appliances,"(£6,444m)",47.54,1.41,JO5F
15,"Hardware, Paints and Glass","(£13,223m)",47.52,2.71,JO5D
16,Music and video recordings and equipment,(£881m),AGG31,0.16,JO5Y
17,Other Specialised Non-food Stores,"(£63,405m)",AGG13,12.99,EAPW
18,Dispensing Chemists,"(£1,515m)",47.73,0.33,JO5K
19,Medical Goods,"(£1,196m)",47.74,0.26,JO5L
20,Cosmetic & Toilet Articles,"(£6,729m)",47.75,1.15,JO5M
21,Computers & Telecomms Equipment,"(£4,031m)",AGG32,0.82,JO5Z
22,Floor Coverings,"(£2,766m)",47.53,0.56,JO5E
23,"Books, Newspapers & Periodicals","(£3,456m)",AGG35,0.68,JO64
24,"Sports Equipment, Games & Toys","(£13,490m)",AGG33,2.87,JO62
25,"Flowers, plants, seeds, fertilisers and pet foods","(£6,563m)",47.76,1.39,JO5N
26,Watches & Jewellery,"(£8,299m)",47.77,1.72,JO5O
27,Other Retail Sale of New Goods in Specialised ...,"(£11,761m)",47.78,2.43,JO5P
28,Second-hand Goods,"(£3,600m)",47.79,0.78,JO5Q
29,Non-store Retail,"(£66,092m)",AGG14,13.03,J5DZ
30,Mail Order,"(£63,064m)",47.91,12.39,JO5R
31,Other Non-store Retail,"(£3,028m)",Agg 11,0.64,JO5S
32,Automotive Fuel,"(£47,956m)",47.3,11.07,JO5A

,category_name,sales_2023,agg_sic,percentage_weight,dataset_code
0,"All Retailing, Including Automotive Fuel","(£509,445m)",AGG21,100,J5C4
1,"All Retailing, Excluding Automotive Fuel","(£461,489m)",AGG21X,88.93,J468
2,Predominantly Food Stores,"(£201,285m)",AGG1,37.57,EAQW
3,Non-specialised Food Stores,"(£184,104m)",47.11,34.57,JO2F
4,Specialist Food Stores,"(£13,803m)",AGG26,2.26,JO32
5,"Alcoholic Drinks, Other Beverages and Tobacco","(£3,378m)",AGG27,0.74,JO33
6,Predominantly Non-food Stores,"(£194,112m)",AGG12,38.33,EAQY
7,Non-Specialised Predominantly Non-Food Stores,"(£37,105m)",47.19,7.11,EAQX
8,"Textile, Clothing, Footwear and Leather","(£56,341m)",AGG5,10.61,EARA
9,Textiles,(£802m),47.51,0.21,JO2I
10,Clothing,"(£48,911m)",47.71,9.28,JO2O
11,Footwear and Leather Goods,"(£6,628m)",47.72,1.12,JO2P
12,Household Goods Stores,"(£37,261m)",AGG7,7.62,EARB
13,"Furniture, Lighting etc","(£16,712m)",47.59,3.34,JO2M
14,Electrical Household Appliances,"(£6,444m)",47.54,1.41,JO2L
15,"Hardware, Paints and Glass","(£13,223m)",47.52,2.71,JO2J
16,Music and video recordings and equipment,(£881m),AGG31,0.16,JO36
17,Other Specialised Non-food Stores,"(£63,405m)",AGG13,12.99,EAQZ
18,Dispensing Chemists,"(£1,515m)",47.73,0.33,JO2Q
19,Medical Goods,"(£1,196m)",47.74,0.26,JO2R
20,Cosmetic & Toilet Articles,"(£6,729m)",47.75,1.15,JO2S
21,Computers & Telecomms Equipment,"(£4,031m)",AGG32,0.82,JO37
22,Floor Coverings,"(£2,766m)",47.53,0.56,JO2K
23,"Books, Newspapers & Periodicals","(£3,456m)",AGG35,0.68,JO3A
24,"Sports Equipment, Games & Toys","(£13,490m)",AGG33,2.87,JO38
25,"Flowers, plants, seeds, fertilisers and pet foods","(£6,563m)",47.76,1.39,JO2T
26,Watches & Jewellery,"(£8,299m)",47.77,1.72,JO2U
27,Other Retail Sale of New Goods in Specialised ...,"(£11,761m)",47.78,2.43,JO2V
28,Second-hand Goods,"(£3,600m)",47.79,0.78,JO2W
29,Non-store Retail,"(£66,092m)",AGG14,13.03,J5BI
30,Mail Order,"(£63,064m)",47.91,12.39,JO2X
31,Other Non-store Retail,"(£3,028m)",Agg 11,0.64,JO2Y
32,Automotive Fuel,"(£47,956m)",47.3,11.07,JO2G

In [210]:
# Transform Commodity Metadata
def transform_commodity_metadata(metadata):
    commodities = pd.DataFrame({
        "commodity_name": metadata.iloc[9, 1:].values,
        "avg_sales_weekly": metadata.iloc[10, 1:].values,
        "agg_sic": metadata.iloc[11, 1:].values,
    })

    return commodities


commodities = transform_commodity_metadata(commodity_metadata)

display(commodities)

                     commodity_name avg_sales_weekly agg_sic
0              Total excluding fuel            8,875    J43S
1  Food, drink and tobacco [Note 3]            3,741    EAWN
2             Clothing and footwear            1,520    EAWO
3          Household goods [Note 3]            1,485    EAWP
4           Other non-food [Note 3]            2,129    EAWQ

In [211]:
# Compare Raw Metadata
print(
    "Volume and value category names match:",
    volume_categories["category_name"].equals(
        value_categories["category_name"]
    )
)

print("Volume categories:", len(volume_categories))
print("Value categories:", len(value_categories))
print("Commodities:", len(commodities))

Volume and value category names match: True
Volume categories: 33
Value categories: 33
Commodities: 5

In [212]:
# Cleaning Retail and Commodity Metadata
def clean_retail_metadata(df):
    df = df.copy()

    df["category_name"] = (
        df["category_name"]
        .astype("string")
        .str.strip()
    )

    df["sales_2023"] = (
        df["sales_2023"]
        .astype("string")
        .str.replace(r"[£(),]", "", regex=True)
        .str.replace("m", "", case=False)
        .str.strip()
    )

    df["sales_2023"] = pd.to_numeric(
        df["sales_2023"],
        errors="coerce"
    )

    df["percentage_weight"] = pd.to_numeric(
        df["percentage_weight"],
        errors="coerce"
    )

    df["agg_sic"] = (
        df["agg_sic"]
        .astype("string")
        .str.strip()
    )

    df["dataset_code"] = (
        df["dataset_code"]
        .astype("string")
        .str.strip()
    )

    return df


volume_categories_clean = clean_retail_metadata(
    volume_categories
)

value_categories_clean = clean_retail_metadata(
    value_categories
)

display(volume_categories_clean)
display(value_categories_clean)

def clean_commodity_metadata(df):
    df = df.copy()

    df["commodity_name"] = (
        df["commodity_name"]
        .astype("string")
        .str.replace(
            r"\s*\[Note \d+\]",
            "",
            regex=True
        )
        .str.strip()
    )

    df["avg_sales_weekly"] = (
        df["avg_sales_weekly"]
        .astype("string")
        .str.replace(",", "", regex=True)
        .str.strip()
    )

    df["avg_sales_weekly"] = pd.to_numeric(
        df["avg_sales_weekly"],
        errors="coerce"
    )

    df["agg_sic"] = (
        df["agg_sic"]
        .astype("string")
        .str.strip()
    )

    return df


commodity_data_clean = clean_commodity_metadata(
    commodities
)

display(commodity_data_clean)

,category_name,sales_2023,agg_sic,percentage_weight,dataset_code
0,"All Retailing, Including Automotive Fuel",509445,AGG21,100.00,J5EK
1,"All Retailing, Excluding Automotive Fuel",461489,AGG21X,88.93,J467
2,Predominantly Food Stores,201285,AGG1,37.57,EAPT
3,Non-specialised Food Stores,184104,47.11,34.57,JO59
4,Specialist Food Stores,13803,AGG26,2.26,JO5U
5,"Alcoholic Drinks, Other Beverages and Tobacco",3378,AGG27,0.74,JO5V
6,Predominantly Non-food Stores,194112,AGG12,38.33,EAPV
7,Non-Specialised Predominantly Non-Food Stores,37105,47.19,7.11,EAPU
8,"Textile, Clothing, Footwear and Leather",56341,AGG5,10.61,EAPX
9,Textiles,802,47.51,0.21,JO5C
10,Clothing,48911,47.71,9.28,JO5I
11,Footwear and Leather Goods,6628,47.72,1.12,JO5J
12,Household Goods Stores,37261,AGG7,7.62,EAPY
13,"Furniture, Lighting etc",16712,47.59,3.34,JO5G
14,Electrical Household Appliances,6444,47.54,1.41,JO5F
15,"Hardware, Paints and Glass",13223,47.52,2.71,JO5D
16,Music and video recordings and equipment,881,AGG31,0.16,JO5Y
17,Other Specialised Non-food Stores,63405,AGG13,12.99,EAPW
18,Dispensing Chemists,1515,47.73,0.33,JO5K
19,Medical Goods,1196,47.74,0.26,JO5L
20,Cosmetic & Toilet Articles,6729,47.75,1.15,JO5M
21,Computers & Telecomms Equipment,4031,AGG32,0.82,JO5Z
22,Floor Coverings,2766,47.53,0.56,JO5E
23,"Books, Newspapers & Periodicals",3456,AGG35,0.68,JO64
24,"Sports Equipment, Games & Toys",13490,AGG33,2.87,JO62
25,"Flowers, plants, seeds, fertilisers and pet foods",6563,47.76,1.39,JO5N
26,Watches & Jewellery,8299,47.77,1.72,JO5O
27,Other Retail Sale of New Goods in Specialised ...,11761,47.78,2.43,JO5P
28,Second-hand Goods,3600,47.79,0.78,JO5Q
29,Non-store Retail,66092,AGG14,13.03,J5DZ
30,Mail Order,63064,47.91,12.39,JO5R
31,Other Non-store Retail,3028,Agg 11,0.64,JO5S
32,Automotive Fuel,47956,47.3,11.07,JO5A

,category_name,sales_2023,agg_sic,percentage_weight,dataset_code
0,"All Retailing, Including Automotive Fuel",509445,AGG21,100.00,J5C4
1,"All Retailing, Excluding Automotive Fuel",461489,AGG21X,88.93,J468
2,Predominantly Food Stores,201285,AGG1,37.57,EAQW
3,Non-specialised Food Stores,184104,47.11,34.57,JO2F
4,Specialist Food Stores,13803,AGG26,2.26,JO32
5,"Alcoholic Drinks, Other Beverages and Tobacco",3378,AGG27,0.74,JO33
6,Predominantly Non-food Stores,194112,AGG12,38.33,EAQY
7,Non-Specialised Predominantly Non-Food Stores,37105,47.19,7.11,EAQX
8,"Textile, Clothing, Footwear and Leather",56341,AGG5,10.61,EARA
9,Textiles,802,47.51,0.21,JO2I
10,Clothing,48911,47.71,9.28,JO2O
11,Footwear and Leather Goods,6628,47.72,1.12,JO2P
12,Household Goods Stores,37261,AGG7,7.62,EARB
13,"Furniture, Lighting etc",16712,47.59,3.34,JO2M
14,Electrical Household Appliances,6444,47.54,1.41,JO2L
15,"Hardware, Paints and Glass",13223,47.52,2.71,JO2J
16,Music and video recordings and equipment,881,AGG31,0.16,JO36
17,Other Specialised Non-food Stores,63405,AGG13,12.99,EAQZ
18,Dispensing Chemists,1515,47.73,0.33,JO2Q
19,Medical Goods,1196,47.74,0.26,JO2R
20,Cosmetic & Toilet Articles,6729,47.75,1.15,JO2S
21,Computers & Telecomms Equipment,4031,AGG32,0.82,JO37
22,Floor Coverings,2766,47.53,0.56,JO2K
23,"Books, Newspapers & Periodicals",3456,AGG35,0.68,JO3A
24,"Sports Equipment, Games & Toys",13490,AGG33,2.87,JO38
25,"Flowers, plants, seeds, fertilisers and pet foods",6563,47.76,1.39,JO2T
26,Watches & Jewellery,8299,47.77,1.72,JO2U
27,Other Retail Sale of New Goods in Specialised ...,11761,47.78,2.43,JO2V
28,Second-hand Goods,3600,47.79,0.78,JO2W
29,Non-store Retail,66092,AGG14,13.03,J5BI
30,Mail Order,63064,47.91,12.39,JO2X
31,Other Non-store Retail,3028,Agg 11,0.64,JO2Y
32,Automotive Fuel,47956,47.3,11.07,JO2G

            commodity_name  avg_sales_weekly agg_sic
0     Total excluding fuel              8875    J43S
1  Food, drink and tobacco              3741    EAWN
2    Clothing and footwear              1520    EAWO
3          Household goods              1485    EAWP
4           Other non-food              2129    EAWQ

In [213]:
# Comparing Retail Categories
print(
    "Volume categories:",
    len(volume_categories_clean)
)

print(
    "Value categories:",
    len(value_categories_clean)
)

print(
    "Same category names:",
    volume_categories_clean["category_name"].equals(
        value_categories_clean["category_name"]
    )
)

print(
    "Same AGG/SIC:",
    volume_categories_clean["agg_sic"].equals(
        value_categories_clean["agg_sic"]
    )
)

print(
    "Same percentage weights:",
    volume_categories_clean["percentage_weight"].equals(
        value_categories_clean["percentage_weight"]
    )
)

print(
    "Same 2023 sales:",
    volume_categories_clean["sales_2023"].equals(
        value_categories_clean["sales_2023"]
    )
)

print(
    "Same dataset codes:",
    volume_categories_clean["dataset_code"].equals(
        value_categories_clean["dataset_code"]
    )
)

comparison = pd.DataFrame({
    "category": volume_categories_clean["category_name"],
    "volume_dataset_code": volume_categories_clean["dataset_code"],
    "value_dataset_code": value_categories_clean["dataset_code"],
})

display(comparison)

Volume categories: 33
Value categories: 33
Same category names: True
Same AGG/SIC: True
Same percentage weights: True
Same 2023 sales: True
Same dataset codes: False

,category,volume_dataset_code,value_dataset_code
0,"All Retailing, Including Automotive Fuel",J5EK,J5C4
1,"All Retailing, Excluding Automotive Fuel",J467,J468
2,Predominantly Food Stores,EAPT,EAQW
3,Non-specialised Food Stores,JO59,JO2F
4,Specialist Food Stores,JO5U,JO32
5,"Alcoholic Drinks, Other Beverages and Tobacco",JO5V,JO33
6,Predominantly Non-food Stores,EAPV,EAQY
7,Non-Specialised Predominantly Non-Food Stores,EAPU,EAQX
8,"Textile, Clothing, Footwear and Leather",EAPX,EARA
9,Textiles,JO5C,JO2I
10,Clothing,JO5I,JO2O
11,Footwear and Leather Goods,JO5J,JO2P
12,Household Goods Stores,EAPY,EARB
13,"Furniture, Lighting etc",JO5G,JO2M
14,Electrical Household Appliances,JO5F,JO2L
15,"Hardware, Paints and Glass",JO5D,JO2J
16,Music and video recordings and equipment,JO5Y,JO36
17,Other Specialised Non-food Stores,EAPW,EAQZ
18,Dispensing Chemists,JO5K,JO2Q
19,Medical Goods,JO5L,JO2R
20,Cosmetic & Toilet Articles,JO5M,JO2S
21,Computers & Telecomms Equipment,JO5Z,JO37
22,Floor Coverings,JO5E,JO2K
23,"Books, Newspapers & Periodicals",JO64,JO3A
24,"Sports Equipment, Games & Toys",JO62,JO38
25,"Flowers, plants, seeds, fertilisers and pet foods",JO5N,JO2T
26,Watches & Jewellery,JO5O,JO2U
27,Other Retail Sale of New Goods in Specialised ...,JO5P,JO2V
28,Second-hand Goods,JO5Q,JO2W
29,Non-store Retail,J5DZ,J5BI
30,Mail Order,JO5R,JO2X
31,Other Non-store Retail,JO5S,JO2Y
32,Automotive Fuel,JO5A,JO2G

In [214]:
# Creating Retail Category Table
retail_category = volume_categories_clean[
    [
        "category_name",
        "agg_sic",
        "percentage_weight",
        "sales_2023",
    ]
].copy()

retail_category.insert(0, "category_id", range(1, len(retail_category) + 1))

display(retail_category)

# Validate Table
print("Rows:", len(retail_category))
print("Duplicate category names:", retail_category["category_name"].duplicated().sum())
print("\nMissing values:", retail_category.isnull().sum())
print("Unique category IDs:", retail_category["category_id"].nunique())
print("Category IDs unique:", retail_category["category_id"].is_unique)

# Export Retail Category Table
retail_category.to_csv("../data/processed/retail_category.csv", index=False)
print("Retail category table exported.")

,category_id,category_name,agg_sic,percentage_weight,sales_2023
0,1,"All Retailing, Including Automotive Fuel",AGG21,100.00,509445
1,2,"All Retailing, Excluding Automotive Fuel",AGG21X,88.93,461489
2,3,Predominantly Food Stores,AGG1,37.57,201285
3,4,Non-specialised Food Stores,47.11,34.57,184104
4,5,Specialist Food Stores,AGG26,2.26,13803
5,6,"Alcoholic Drinks, Other Beverages and Tobacco",AGG27,0.74,3378
6,7,Predominantly Non-food Stores,AGG12,38.33,194112
7,8,Non-Specialised Predominantly Non-Food Stores,47.19,7.11,37105
8,9,"Textile, Clothing, Footwear and Leather",AGG5,10.61,56341
9,10,Textiles,47.51,0.21,802
10,11,Clothing,47.71,9.28,48911
11,12,Footwear and Leather Goods,47.72,1.12,6628
12,13,Household Goods Stores,AGG7,7.62,37261
13,14,"Furniture, Lighting etc",47.59,3.34,16712
14,15,Electrical Household Appliances,47.54,1.41,6444
15,16,"Hardware, Paints and Glass",47.52,2.71,13223
16,17,Music and video recordings and equipment,AGG31,0.16,881
17,18,Other Specialised Non-food Stores,AGG13,12.99,63405
18,19,Dispensing Chemists,47.73,0.33,1515
19,20,Medical Goods,47.74,0.26,1196
20,21,Cosmetic & Toilet Articles,47.75,1.15,6729
21,22,Computers & Telecomms Equipment,AGG32,0.82,4031
22,23,Floor Coverings,47.53,0.56,2766
23,24,"Books, Newspapers & Periodicals",AGG35,0.68,3456
24,25,"Sports Equipment, Games & Toys",AGG33,2.87,13490
25,26,"Flowers, plants, seeds, fertilisers and pet foods",47.76,1.39,6563
26,27,Watches & Jewellery,47.77,1.72,8299
27,28,Other Retail Sale of New Goods in Specialised ...,47.78,2.43,11761
28,29,Second-hand Goods,47.79,0.78,3600
29,30,Non-store Retail,AGG14,13.03,66092
30,31,Mail Order,47.91,12.39,63064
31,32,Other Non-store Retail,Agg 11,0.64,3028
32,33,Automotive Fuel,47.3,11.07,47956

Rows: 33
Duplicate category names: 0

Missing values: category_id          0
category_name        0
agg_sic              0
percentage_weight    0
sales_2023           0
dtype: int64
Unique category IDs: 33
Category IDs unique: True
Retail category table exported.

In [215]:
# Extract Raw Retail Data
def extract_monthly_data(df, start_row=11, end_row=472):
    return df.iloc[start_row:end_row + 1].copy()

volume_monthly_raw = extract_monthly_data(volume)
value_monthly_raw = extract_monthly_data(value)

display(volume_monthly_raw.head())
display(value_monthly_raw.head())

,"1M - CHAINED VOLUME OF RETAIL SALES SEASONALLY ADJUSTED, Index numbers of sales per week and percentage increase on a year earlier, SIC 2007",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
11,1988 Jan,NaN,51.4,63.8,50.0,156.0,454.3,48.8,50.9,36.9,109.3,34.4,44.2,66.9,81.6,42.1,72.6,199.1,49.5,154.1,57.3,24.2,28.1,199.4,284.5,14.3,37.2,41.9,55.2,56.5,28.1,16.2,412.9,NaN
12,1988 Feb,NaN,50.3,63.5,50.0,152.4,446.3,47.5,50.3,36.1,108.2,33.5,44.6,65.1,81.5,39.8,70.7,189.5,47.4,143.9,52.5,23.6,25.2,196.9,280.9,13.8,35.9,40.4,53.2,55.7,26.8,15.2,402.9,NaN
13,1988 Mar,NaN,50.3,63.1,49.6,149.9,455.4,47.6,50.4,35.7,106.3,33.3,43.0,65.6,81.6,40.7,70.2,194.8,47.8,155.1,54.9,23.9,25.1,194.8,286.0,13.8,35.9,40.7,54.3,54.2,26.9,15.4,400.4,NaN
14,1988 Apr,NaN,51.6,64.3,50.8,152.9,452.6,48.9,51.0,36.5,106.6,34.0,44.1,67.2,85.1,41.0,71.3,197.0,49.9,154.4,55.5,24.3,28.9,205.2,288.8,14.4,37.1,41.4,54.4,57.1,28.5,16.5,416.4,NaN
15,1988 May,NaN,51.3,63.7,50.3,151.5,450.7,48.6,50.8,36.1,108.3,33.5,44.5,67.6,85.5,41.5,71.6,198.0,49.4,158.6,56.8,24.7,27.5,207.2,286.4,14.2,37.2,41.1,54.0,57.8,28.2,15.9,432.8,NaN

,"2M - VALUE OF RETAIL SALES AT CURRENT PRICES SEASONALLY ADJUSTED, Index numbers of sales per week and percentage increase on a year earlier, SIC 2007",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
11,1988 Jan,NaN,27.0,23.3,18.3,61.2,136.5,34.9,30.2,31.9,88.5,29.3,44.3,48.6,41.4,85.1,32.6,159.6,32.3,64.9,23.9,11.8,87.8,72.9,87.5,18.4,18.4,15.6,33.6,26.0,15.3,10.8,110.5,NaN
12,1988 Feb,NaN,26.6,23.2,18.4,59.8,133.7,34.2,30.0,31.5,86.1,28.8,44.8,47.5,41.9,80.4,31.7,151.4,31.1,60.6,18.7,11.3,78.0,72.5,88.5,17.8,17.9,15.2,32.6,25.8,14.8,10.3,107.9,NaN
13,1988 Mar,NaN,26.6,23.2,18.4,59.4,136.8,34.2,30.1,31.2,85.4,28.7,43.3,47.9,41.8,82.3,31.6,154.6,31.1,65.5,21.0,11.5,73.9,71.4,89.7,17.7,18.0,15.2,33.2,25.1,14.8,10.4,108.1,NaN
14,1988 Apr,NaN,27.4,23.7,18.9,60.2,136.1,35.1,30.4,31.5,83.3,28.9,44.3,48.7,43.3,82.6,31.9,156.4,33.1,65.8,22.2,11.8,96.3,75.2,90.7,18.4,18.5,15.6,33.2,26.3,15.9,11.2,112.2,NaN
15,1988 May,NaN,27.3,23.5,18.7,59.9,136.2,35.3,30.5,32.1,85.2,29.4,45.6,49.4,43.8,84.2,32.5,157.2,32.7,67.8,22.1,12.2,87.1,75.9,90.5,18.4,18.6,15.5,33.3,26.7,15.6,10.7,116.6,NaN

In [216]:
# Inspect Raw Monthly Data
print("Volume: ", volume_monthly_raw.shape)
print("Value: ", value_monthly_raw.shape)

# Inspect first and last periods
print(volume_monthly_raw.iloc[0, 0])
print(volume_monthly_raw.iloc[-1, 0])

print(value_monthly_raw.iloc[0, 0])
print(value_monthly_raw.iloc[-1, 0])

Volume:  (462, 34)
Value:  (462, 34)
1988 Jan
2026 Jun
1988 Jan
2026 Jun

In [217]:
# Transform time_period to dim_date
def transform_time_period(df):
    df = df.copy()

    df = df.rename(
        columns={
            df.columns[0]: "time_period"
        }
    )

    df["time_period"] = pd.to_datetime(
        df["time_period"],
        format="%Y %b",
        errors="coerce"
    )

    return df


volume_monthly_raw = transform_time_period(
    volume_monthly_raw
)

value_monthly_raw = transform_time_period(
    value_monthly_raw
)

# Create date_id
def create_date_id(df):
    df = df.copy()

    df["date_id"] = (
        df["time_period"].dt.year * 100
        + df["time_period"].dt.month
    )

    return df


volume_monthly_raw = create_date_id(
    volume_monthly_raw
)

value_monthly_raw = create_date_id(
    value_monthly_raw
)

# Validate changes
display(
    volume_monthly_raw[
        ["date_id", "time_period"]
    ].head()
)

display(
    value_monthly_raw[
        ["date_id", "time_period"]
    ].head()
)

# Check Uniqueness
print(volume_monthly_raw["date_id"].is_unique)
print(value_monthly_raw["date_id"].is_unique)

    date_id time_period
11   198801  1988-01-01
12   198802  1988-02-01
13   198803  1988-03-01
14   198804  1988-04-01
15   198805  1988-05-01

    date_id time_period
11   198801  1988-01-01
12   198802  1988-02-01
13   198803  1988-03-01
14   198804  1988-04-01
15   198805  1988-05-01

True
True

In [218]:
# Rename Monthly Category Columns
def rename_category_columns(df, metadata):
    df = df.copy()

    category_names = metadata.iloc[6, 1:].tolist()

    monthly_category_columns = df.columns[1:-1]

    if len(monthly_category_columns) != len(category_names):
        raise ValueError(
            f"Category mismatch: "
            f"{len(monthly_category_columns)} monthly columns vs "
            f"{len(category_names)} metadata categories"
        )

    column_mapping = dict(
        zip(monthly_category_columns, category_names)
    )

    df = df.rename(columns=column_mapping)

    return df

volume_monthly_raw = rename_category_columns(
    volume_monthly_raw,
    volume_metadata
)

value_monthly_raw = rename_category_columns(
    value_monthly_raw,
    value_metadata
)

print("Volume columns:", len(volume_monthly_raw.columns))
print("Value columns:", len(value_monthly_raw.columns))

display(volume_monthly_raw.head())
display(value_monthly_raw.head())

Volume columns: 35
Value columns: 35

,time_period,"All Retailing, Including Automotive Fuel","All Retailing, Excluding Automotive Fuel",Predominantly Food Stores,Non-specialised Food Stores,Specialist Food Stores,"Alcoholic Drinks, Other Beverages and Tobacco",Predominantly Non-food Stores,Non-Specialised Predominantly Non-Food Stores,"Textile, Clothing, Footwear and Leather",Textiles,Clothing,Footwear and Leather Goods,Household Goods Stores,"Furniture, Lighting etc",Electrical Household Appliances,"Hardware, Paints and Glass",Music and video recordings and equipment,Other Specialised Non-food Stores,Dispensing Chemists,Medical Goods,Cosmetic & Toilet Articles,Computers & Telecomms Equipment,Floor Coverings,"Books, Newspapers & Periodicals","Sports Equipment, Games & Toys","Flowers, plants, seeds, fertilisers and pet foods",Watches & Jewellery,Other Retail Sale of New Goods in Specialised Stores,Second-hand Goods,Non-store Retail,Mail Order,Other Non-store Retail,Automotive Fuel,date_id
11,1988-01-01,NaN,51.4,63.8,50.0,156.0,454.3,48.8,50.9,36.9,109.3,34.4,44.2,66.9,81.6,42.1,72.6,199.1,49.5,154.1,57.3,24.2,28.1,199.4,284.5,14.3,37.2,41.9,55.2,56.5,28.1,16.2,412.9,NaN,198801
12,1988-02-01,NaN,50.3,63.5,50.0,152.4,446.3,47.5,50.3,36.1,108.2,33.5,44.6,65.1,81.5,39.8,70.7,189.5,47.4,143.9,52.5,23.6,25.2,196.9,280.9,13.8,35.9,40.4,53.2,55.7,26.8,15.2,402.9,NaN,198802
13,1988-03-01,NaN,50.3,63.1,49.6,149.9,455.4,47.6,50.4,35.7,106.3,33.3,43.0,65.6,81.6,40.7,70.2,194.8,47.8,155.1,54.9,23.9,25.1,194.8,286.0,13.8,35.9,40.7,54.3,54.2,26.9,15.4,400.4,NaN,198803
14,1988-04-01,NaN,51.6,64.3,50.8,152.9,452.6,48.9,51.0,36.5,106.6,34.0,44.1,67.2,85.1,41.0,71.3,197.0,49.9,154.4,55.5,24.3,28.9,205.2,288.8,14.4,37.1,41.4,54.4,57.1,28.5,16.5,416.4,NaN,198804
15,1988-05-01,NaN,51.3,63.7,50.3,151.5,450.7,48.6,50.8,36.1,108.3,33.5,44.5,67.6,85.5,41.5,71.6,198.0,49.4,158.6,56.8,24.7,27.5,207.2,286.4,14.2,37.2,41.1,54.0,57.8,28.2,15.9,432.8,NaN,198805

,time_period,"All Retailing, Including Automotive Fuel","All Retailing, Excluding Automotive Fuel",Predominantly Food Stores,Non-specialised Food Stores,Specialist Food Stores,"Alcoholic Drinks, Other Beverages and Tobacco",Predominantly Non-food Stores,Non-Specialised Predominantly Non-Food Stores,"Textile, Clothing, Footwear and Leather",Textiles,Clothing,Footwear and Leather Goods,Household Goods Stores,"Furniture, Lighting etc",Electrical Household Appliances,"Hardware, Paints and Glass",Music and video recordings and equipment,Other Specialised Non-food Stores,Dispensing Chemists,Medical Goods,Cosmetic & Toilet Articles,Computers & Telecomms Equipment,Floor Coverings,"Books, Newspapers & Periodicals","Sports Equipment, Games & Toys","Flowers, plants, seeds, fertilisers and pet foods",Watches & Jewellery,Other Retail Sale of New Goods in Specialised Stores,Second-hand Goods,Non-store Retail,Mail Order,Other Non-store Retail,Automotive Fuel,date_id
11,1988-01-01,NaN,27.0,23.3,18.3,61.2,136.5,34.9,30.2,31.9,88.5,29.3,44.3,48.6,41.4,85.1,32.6,159.6,32.3,64.9,23.9,11.8,87.8,72.9,87.5,18.4,18.4,15.6,33.6,26.0,15.3,10.8,110.5,NaN,198801
12,1988-02-01,NaN,26.6,23.2,18.4,59.8,133.7,34.2,30.0,31.5,86.1,28.8,44.8,47.5,41.9,80.4,31.7,151.4,31.1,60.6,18.7,11.3,78.0,72.5,88.5,17.8,17.9,15.2,32.6,25.8,14.8,10.3,107.9,NaN,198802
13,1988-03-01,NaN,26.6,23.2,18.4,59.4,136.8,34.2,30.1,31.2,85.4,28.7,43.3,47.9,41.8,82.3,31.6,154.6,31.1,65.5,21.0,11.5,73.9,71.4,89.7,17.7,18.0,15.2,33.2,25.1,14.8,10.4,108.1,NaN,198803
14,1988-04-01,NaN,27.4,23.7,18.9,60.2,136.1,35.1,30.4,31.5,83.3,28.9,44.3,48.7,43.3,82.6,31.9,156.4,33.1,65.8,22.2,11.8,96.3,75.2,90.7,18.4,18.5,15.6,33.2,26.3,15.9,11.2,112.2,NaN,198804
15,1988-05-01,NaN,27.3,23.5,18.7,59.9,136.2,35.3,30.5,32.1,85.2,29.4,45.6,49.4,43.8,84.2,32.5,157.2,32.7,67.8,22.1,12.2,87.1,75.9,90.5,18.4,18.6,15.5,33.3,26.7,15.6,10.7,116.6,NaN,198805

In [219]:
# Transform Monthly Data
def transform_monthly_data(df, value_name):
    df = df.copy()

    id_columns = [
        "date_id",
        "time_period"
    ]

    value_columns = [
        col
        for col in df.columns
        if col not in id_columns
    ]

    df = df.melt(
        id_vars=id_columns,
        value_vars=value_columns,
        var_name="category_name",
        value_name=value_name
    )

    return df


volume_monthly = transform_monthly_data(volume_monthly_raw, "volume_index")
value_monthly = transform_monthly_data(value_monthly_raw, "sales_value")

display(volume_monthly.head(20))
display(value_monthly.head(20))

    date_id time_period                             category_name volume_index
0    198801  1988-01-01  All Retailing, Including Automotive Fuel          NaN
1    198802  1988-02-01  All Retailing, Including Automotive Fuel          NaN
2    198803  1988-03-01  All Retailing, Including Automotive Fuel          NaN
3    198804  1988-04-01  All Retailing, Including Automotive Fuel          NaN
4    198805  1988-05-01  All Retailing, Including Automotive Fuel          NaN
5    198806  1988-06-01  All Retailing, Including Automotive Fuel          NaN
6    198807  1988-07-01  All Retailing, Including Automotive Fuel          NaN
7    198808  1988-08-01  All Retailing, Including Automotive Fuel          NaN
8    198809  1988-09-01  All Retailing, Including Automotive Fuel          NaN
9    198810  1988-10-01  All Retailing, Including Automotive Fuel          NaN
10   198811  1988-11-01  All Retailing, Including Automotive Fuel          NaN
11   198812  1988-12-01  All Retailing, Including Automotive Fuel          NaN
12   198901  1989-01-01  All Retailing, Including Automotive Fuel          NaN
13   198902  1989-02-01  All Retailing, Including Automotive Fuel          NaN
14   198903  1989-03-01  All Retailing, Including Automotive Fuel          NaN
15   198904  1989-04-01  All Retailing, Including Automotive Fuel          NaN
16   198905  1989-05-01  All Retailing, Including Automotive Fuel          NaN
17   198906  1989-06-01  All Retailing, Including Automotive Fuel          NaN
18   198907  1989-07-01  All Retailing, Including Automotive Fuel          NaN
19   198908  1989-08-01  All Retailing, Including Automotive Fuel          NaN

    date_id time_period                             category_name sales_value
0    198801  1988-01-01  All Retailing, Including Automotive Fuel         NaN
1    198802  1988-02-01  All Retailing, Including Automotive Fuel         NaN
2    198803  1988-03-01  All Retailing, Including Automotive Fuel         NaN
3    198804  1988-04-01  All Retailing, Including Automotive Fuel         NaN
4    198805  1988-05-01  All Retailing, Including Automotive Fuel         NaN
5    198806  1988-06-01  All Retailing, Including Automotive Fuel         NaN
6    198807  1988-07-01  All Retailing, Including Automotive Fuel         NaN
7    198808  1988-08-01  All Retailing, Including Automotive Fuel         NaN
8    198809  1988-09-01  All Retailing, Including Automotive Fuel         NaN
9    198810  1988-10-01  All Retailing, Including Automotive Fuel         NaN
10   198811  1988-11-01  All Retailing, Including Automotive Fuel         NaN
11   198812  1988-12-01  All Retailing, Including Automotive Fuel         NaN
12   198901  1989-01-01  All Retailing, Including Automotive Fuel         NaN
13   198902  1989-02-01  All Retailing, Including Automotive Fuel         NaN
14   198903  1989-03-01  All Retailing, Including Automotive Fuel         NaN
15   198904  1989-04-01  All Retailing, Including Automotive Fuel         NaN
16   198905  1989-05-01  All Retailing, Including Automotive Fuel         NaN
17   198906  1989-06-01  All Retailing, Including Automotive Fuel         NaN
18   198907  1989-07-01  All Retailing, Including Automotive Fuel         NaN
19   198908  1989-08-01  All Retailing, Including Automotive Fuel         NaN

In [220]:
# Match Category Names and ID
category_lookup = retail_category[
    [
        "category_id",
        "category_name"
    ]
].copy()


volume_monthly = volume_monthly.merge(
    category_lookup,
    on="category_name",
    how="left",
    validate="many_to_one"
)

value_monthly = value_monthly.merge(
    category_lookup,
    on="category_name",
    how="left",
    validate="many_to_one"
)

# Validate
print("Missing volume category IDs:", volume_monthly["category_id"].isna().sum())
print("Missing value category IDs:", value_monthly["category_id"].isna().sum())

Missing volume category IDs: 0
Missing value category IDs: 0

In [221]:
# Add Dataset Codes

volume_monthly = volume_monthly.merge(
    volume_categories_clean[
        [
            "category_name",
            "dataset_code"
        ]
    ],
    on="category_name",
    how="left",
    validate="many_to_one"
)

volume_monthly = volume_monthly.rename(
    columns={
        "dataset_code": "volume_code"
    }
)

value_monthly = value_monthly.merge(
    value_categories_clean[
        [
            "category_name",
            "dataset_code"
        ]
    ],
    on="category_name",
    how="left",
    validate="many_to_one"
)

value_monthly = value_monthly.rename(
    columns={
        "dataset_code": "value_code"
    }
)

In [222]:
# Create Volume and Value Table

volume_monthly = volume_monthly[
    [
        "date_id",
        "time_period",
        "category_id",
        "volume_code",
        "volume_index",
    ]
]

value_monthly = value_monthly[
    [
        "date_id",
        "time_period",
        "category_id",
        "value_code",
        "sales_value",
    ]
]

volume_monthly["volume_index"] = pd.to_numeric(
    volume_monthly["volume_index"],
    errors="coerce"
)

value_monthly["sales_value"] = pd.to_numeric(
    value_monthly["sales_value"],
    errors="coerce"
)

display(volume_monthly.head())
display(value_monthly.head())

print(volume_monthly.shape)
print(value_monthly.shape)

print(
    "Duplicate volume keys:",
    volume_monthly.duplicated(
        ["date_id", "category_id"]
    ).sum()
)

print(
    "Duplicate value keys:",
    value_monthly.duplicated(
        ["date_id", "category_id"]
    ).sum()
)

   date_id time_period  category_id volume_code  volume_index
0   198801  1988-01-01            1        J5EK           NaN
1   198802  1988-02-01            1        J5EK           NaN
2   198803  1988-03-01            1        J5EK           NaN
3   198804  1988-04-01            1        J5EK           NaN
4   198805  1988-05-01            1        J5EK           NaN

   date_id time_period  category_id value_code  sales_value
0   198801  1988-01-01            1       J5C4          NaN
1   198802  1988-02-01            1       J5C4          NaN
2   198803  1988-03-01            1       J5C4          NaN
3   198804  1988-04-01            1       J5C4          NaN
4   198805  1988-05-01            1       J5C4          NaN

(15246, 5)
(15246, 5)
Duplicate volume keys: 0
Duplicate value keys: 0

In [223]:
# Validate

print("--- Volume validation ---")
print("Rows:", len(volume_monthly))
print("Missing values:")
print(volume_monthly.isna().sum())
print(
    "Duplicate keys:",
    volume_monthly.duplicated(["date_id", "category_id"]).sum()
)

print("\n--- Value validation ---")
print("Rows:", len(value_monthly))
print("Missing values:")
print(value_monthly.isna().sum())
print(
    "Duplicate keys:",
    value_monthly.duplicated(["date_id", "category_id"]).sum()
)

print(
    "Volume missing category IDs:",
    volume_monthly["category_id"].isna().sum()
)

print(
    "Value missing category IDs:",
    value_monthly["category_id"].isna().sum()
)

print(volume_monthly.columns.tolist())
print(value_monthly.columns.tolist())

--- Volume validation ---
Rows: 15246
Missing values:
date_id           0
time_period       0
category_id       0
volume_code       0
volume_index    192
dtype: int64
Duplicate keys: 0

--- Value validation ---
Rows: 15246
Missing values:
date_id          0
time_period      0
category_id      0
value_code       0
sales_value    192
dtype: int64
Duplicate keys: 0
Volume missing category IDs: 0
Value missing category IDs: 0
['date_id', 'time_period', 'category_id', 'volume_code', 'volume_index']
['date_id', 'time_period', 'category_id', 'value_code', 'sales_value']

In [224]:
# Export Monthly Retail Data

volume_monthly.to_csv("../data/processed/retail_volume_monthly.csv", index=False)

value_monthly.to_csv("../data/processed/retail_value_monthly.csv", index=False)